# Generated by Django 3.2.4 on 2021-06-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birthday',
            new_name='birthdate',
        ),
    ]
